### PR TITLE
Delete render.yaml

### PR DESCRIPTION
**Pull request by juliahw**
The sync is failing because the service doesn't exist anymore.

### CODE REVIEW

**Comment by wmoss** [comment]
I'm confused it does exist: https://dashboard.render.com/env-group/evg-ceh34rp4reb94c728v2g

**Comment by wmoss** [comment]
Oh wait, that's an environment group of the same name 🤦

**Comment by wmoss** [comment]
Can we instead update it to reflect the two new instances?
* `pgbouncer-prod-ssl-2`
* `global-db-pgbouncer-ssl`

**Comment by juliahw** [comment]
Oh actually looks like @kyle-watershed beat me to it. https://github.com/watershed-climate/docker-pgbouncer/pull/3/files

**Pull request closed without merging**
